#pragma checksum "/Users/bryannabrueggman/Projects/PopQuiz/PopQuiz/Views/PopQuiz/About.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "5bd23b657206f03355107aa32261a89d16af1350"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_PopQuiz_About), @"mvc.1.0.view", @"/Views/PopQuiz/About.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Views/PopQuiz/About.cshtml", typeof(AspNetCore.Views_PopQuiz_About))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#line 1 "/Users/bryannabrueggman/Projects/PopQuiz/PopQuiz/Views/_ViewImports.cshtml"
using PopQuiz;

#line default
#line hidden
#line 2 "/Users/bryannabrueggman/Projects/PopQuiz/PopQuiz/Views/_ViewImports.cshtml"
using PopQuiz.Models;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"5bd23b657206f03355107aa32261a89d16af1350", @"/Views/PopQuiz/About.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"2cb5fb30ee48c5bba2dffa7a147490e2909a50fc", @"/Views/_ViewImports.cshtml")]
    public class Views_PopQuiz_About : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            BeginContext(0, 114, true);
            WriteLiteral("<header>\r\n    <h1>Heres a Header</h1>\r\n</header>\r\n\r\n\r\n<footer>\r\n    <p>Done By: Bryanna Brueggman</p>\r\n\r\n</footer>");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
